In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Files/ceased operations.csv')
columns = ['Industry', 'Gender_ethnicity', 'Ceased_reasons', 'Total_firms', 'Total_sales']
df.columns = columns
df = df.drop(columns = 'Total_sales')
df.head()

,Industry,Gender_ethnicity,Ceased_reasons,Total_firms
0,Total for all sectors,All firms,All firms,27626360
1,Total for all sectors,All firms,Business is currently operating,13754386
2,Total for all sectors,All firms,Operations ceased because owner(s) military de...,3837
3,Total for all sectors,All firms,Operations ceased because owner(s) illness or ...,206979
4,Total for all sectors,All firms,Operations ceased because owner(s) retired,438109

In [3]:
#Check data types
df.dtypes

Industry            object
Gender_ethnicity    object
Ceased_reasons      object
Total_firms          int64
dtype: object

In [4]:
#Create df just with all firms
new_df = df.loc[df['Industry'] == 'Total for all sectors']
new_df = new_df.loc[new_df['Gender_ethnicity'] == 'All firms']
new_df = new_df.iloc[1:]
new_df

,Industry,Gender_ethnicity,Ceased_reasons,Total_firms
1,Total for all sectors,All firms,Business is currently operating,13754386
2,Total for all sectors,All firms,Operations ceased because owner(s) military de...,3837
3,Total for all sectors,All firms,Operations ceased because owner(s) illness or ...,206979
4,Total for all sectors,All firms,Operations ceased because owner(s) retired,438109
5,Total for all sectors,All firms,Operations ceased because owner(s) died,47671
6,Total for all sectors,All firms,Operations ceased because operated for a speci...,284556
7,Total for all sectors,All firms,Operations ceased due to inadequate cash flow ...,791597
8,Total for all sectors,All firms,Operations ceased due to lack of business loan...,90916
9,Total for all sectors,All firms,Operations ceased due to lack of personal loan...,54323
10,Total for all sectors,All firms,Operations ceased because owner(s) started ano...,116075
11,Total for all sectors,All firms,Operations ceased because owner(s) sold the bu...,131993
12,Total for all sectors,All firms,Operations ceased for another reason,1797527
13,Total for all sectors,All firms,Total reporting,17346886
14,Total for all sectors,All firms,Operating status not reported,176700
15,Total for all sectors,All firms,Reason operations ceased not reported,25480

In [46]:
#Remove all firms?
df_grouped = new_df.groupby('Ceased_reasons').sum()
df_grouped = df_grouped.sort_values('Total_firms', ascending = False)
df_grouped['Percentage'] = round(df_grouped['Total_firms']/df_grouped.iloc[0,0]*100,2)
df_grouped

                                                    Total_firms  Percentage
Ceased_reasons
Total reporting                                        17346886      100.00
Business is currently operating                        13754386       79.29
Operations ceased for another reason                    1797527       10.36
Operations ceased due to inadequate cash flow o...       791597        4.56
Operations ceased because owner(s) retired               438109        2.53
Operations ceased because operated for a specif...       284556        1.64
Operations ceased because owner(s) illness or i...       206979        1.19
Operating status not reported                            176700        1.02
Operations ceased because owner(s) sold the bus...       131993        0.76
Operations ceased because owner(s) started anot...       116075        0.67
Operations ceased due to lack of business loans...        90916        0.52
Operations ceased due to lack of personal loans...        54323        0.31
Operations ceased because owner(s) died                   47671        0.27
Reason operations ceased not reported                     25480        0.15
Operations ceased because owner(s) military dep...         3837        0.02

In [26]:
# Need to add a percentage column after Total_firms
df_multi_gender = df.set_index(['Gender_ethnicity', 'Ceased_reasons'])
df_multi_gender = df_multi_gender.loc[df_multi_gender['Industry'] == 'Total for all sectors']
df_multi_gender = df_multi_gender.drop(columns = 'Industry')
df_multi_gender

                                                                                                       Total_firms
Gender_ethnicity                                   Ceased_reasons
All firms                                          All firms                                              27626360
                                                   Business is currently operating                        13754386
                                                   Operations ceased because owner(s) military dep...         3837
                                                   Operations ceased because owner(s) illness or i...       206979
                                                   Operations ceased because owner(s) retired               438109
                                                   Operations ceased because owner(s) died                   47671
                                                   Operations ceased because operated for a specif...       284556
                                                   Operations ceased due to inadequate cash flow o...       791597
                                                   Operations ceased due to lack of business loans...        90916
                                                   Operations ceased due to lack of personal loans...        54323
                                                   Operations ceased because owner(s) started anot...       116075
                                                   Operations ceased because owner(s) sold the bus...       131993
                                                   Operations ceased for another reason                    1797527
                                                   Total reporting                                        17346886
                                                   Operating status not reported                            176700
                                                   Reason operations ceased not reported                     25480
Female-owned                                       All firms                                               9878397
                                                   Business is currently operating                         4215931
                                                   Operations ceased because owner(s) military dep...         1066
                                                   Operations ceased because owner(s) illness or i...        80740
                                                   Operations ceased because owner(s) retired               143287
                                                   Operations ceased because owner(s) died                   13164
                                                   Operations ceased because operated for a specif...       118176
                                                   Operations ceased due to inadequate cash flow o...       306103
                                                   Operations ceased due to lack of business loans...        25372
                                                   Operations ceased due to lack of personal loans...        16092
                                                   Operations ceased because owner(s) started anot...        36863
                                                   Operations ceased because owner(s) sold the bus...        28383
                                                   Operations ceased for another reason                     819327
                                                   Total reporting                                         5679749
...                                                                                                            ...
All firms classifiable by gender, ethnicity, ra... Operations ceased because owner(s) military dep...         3616
                                                   Operations ceased because owner(s) illness or i...       203861
                                                   Operations ceased because owner(s) retired               434387
                                                   Operations ceased because owner(s) died                   45817
                                                   Operations ceased because operated for a specif...       281718
                                                   Operations ceased due to inadequate cash flow o...       781082
                                                   Operations ceased due to lack of business loans...        88654
                                                   Operations ceased due to lack of personal loans...        53350
                                                   Operations ceased because owner(s) started anot...       114842
                                                   Operations ceased because owner(s) sold the bus...       122468
                                                   Operations ceased for another reason                    1747308
                                                   Total reporting                                        17008442
                                                   Operating status not reported                            167355
                                                   Reason operations ceased not reported                     20405
Publicly held and other firms not classifiable ... All firms                                                446980
                                                   Business is currently operating                          253851
                                                   Operations ceased because owner(s) military dep...          221
                                                   Operations ceased because owner(s) illness or i...         3118
                                                   Operations ceased because owner(s) retired                 3722
                                                   Operations ceased because owner(s) died                    1854
                                                   Operations ceased because operated for a specif...         2838
                                                   Operations ceased due to inadequate cash flow o...        10516
                                                   Operations ceased due to lack of business loans...         2262
                                                   Operations ceased due to lack of personal loans...          973
                                                   Operations ceased because owner(s) started anot...         1233
                                                   Operations ceased because owner(s) sold the bus...         9525
                                                   Operations ceased for another reason                      50219
                                                   Total reporting                                          338443
                                                   Operating status not reported                              9345
                                                   Reason operations ceased not reported                      5075

[1632 rows x 1 columns]

In [33]:
#Female
df_female = df_multi_gender.loc[pd.IndexSlice['Female-owned',:],:]
df_female = df_female.iloc[1:]
df_female = df_female.sort_values('Total_firms', ascending = False)
df_female['Percentage'] = round(df_female['Total_firms']/df_female.iloc[0,0]*100,2)
df_female

                                                                     Total_firms  \
Gender_ethnicity Ceased_reasons
Female-owned     Total reporting                                         5679749
                 Business is currently operating                         4215931
                 Operations ceased for another reason                     819327
                 Operations ceased due to inadequate cash flow o...       306103
                 Operations ceased because owner(s) retired               143287
                 Operations ceased because operated for a specif...       118176
                 Operations ceased because owner(s) illness or i...        80740
                 Operating status not reported                             66895
                 Operations ceased because owner(s) started anot...        36863
                 Operations ceased because owner(s) sold the bus...        28383
                 Operations ceased due to lack of business loans...        25372
                 Operations ceased due to lack of personal loans...        16092
                 Operations ceased because owner(s) died                   13164
                 Reason operations ceased not reported                      8392
                 Operations ceased because owner(s) military dep...         1066

                                                                     Percentage
Gender_ethnicity Ceased_reasons
Female-owned     Total reporting                                         100.00
                 Business is currently operating                          74.23
                 Operations ceased for another reason                     14.43
                 Operations ceased due to inadequate cash flow o...        5.39
                 Operations ceased because owner(s) retired                2.52
                 Operations ceased because operated for a specif...        2.08
                 Operations ceased because owner(s) illness or i...        1.42
                 Operating status not reported                             1.18
                 Operations ceased because owner(s) started anot...        0.65
                 Operations ceased because owner(s) sold the bus...        0.50
                 Operations ceased due to lack of business loans...        0.45
                 Operations ceased due to lack of personal loans...        0.28
                 Operations ceased because owner(s) died                   0.23
                 Reason operations ceased not reported                     0.15
                 Operations ceased because owner(s) military dep...        0.02

In [34]:
#Male
df_male = df_multi_gender.loc[pd.IndexSlice['Male-owned',:],:]
df_male = df_male.iloc[1:]
df_male = df_male.sort_values('Total_firms', ascending = False)
df_male['Percentage'] = round(df_male['Total_firms']/df_male.iloc[0,0]*100,2)
df_male

                                                                     Total_firms  \
Gender_ethnicity Ceased_reasons
Male-owned       Total reporting                                         9460960
                 Business is currently operating                         7653614
                 Operations ceased for another reason                     835147
                 Operations ceased due to inadequate cash flow o...       402027
                 Operations ceased because owner(s) retired               253778
                 Operations ceased because operated for a specif...       152975
                 Operations ceased because owner(s) illness or i...       107537
                 Operating status not reported                             92608
                 Operations ceased because owner(s) sold the bus...        72571
                 Operations ceased because owner(s) started anot...        68366
                 Operations ceased due to lack of business loans...        53741
                 Operations ceased due to lack of personal loans...        31372
                 Operations ceased because owner(s) died                   27813
                 Reason operations ceased not reported                     10849
                 Operations ceased because owner(s) military dep...         2328

                                                                     Percentage
Gender_ethnicity Ceased_reasons
Male-owned       Total reporting                                         100.00
                 Business is currently operating                          80.90
                 Operations ceased for another reason                      8.83
                 Operations ceased due to inadequate cash flow o...        4.25
                 Operations ceased because owner(s) retired                2.68
                 Operations ceased because operated for a specif...        1.62
                 Operations ceased because owner(s) illness or i...        1.14
                 Operating status not reported                             0.98
                 Operations ceased because owner(s) sold the bus...        0.77
                 Operations ceased because owner(s) started anot...        0.72
                 Operations ceased due to lack of business loans...        0.57
                 Operations ceased due to lack of personal loans...        0.33
                 Operations ceased because owner(s) died                   0.29
                 Reason operations ceased not reported                     0.11
                 Operations ceased because owner(s) military dep...        0.02

In [42]:
#White
df_white = df_multi_gender.loc[pd.IndexSlice['White',:],:]
df_white = df_white.iloc[1:]
df_white = df_white.sort_values('Total_firms', ascending = False)
df_white['Percentage'] = round(df_white['Total_firms']/df_white.iloc[0,0]*100,2)
df_white

                                                                     Total_firms  \
Gender_ethnicity Ceased_reasons
White            Total reporting                                        14664457
                 Business is currently operating                        11753216
                 Operations ceased for another reason                    1436998
                 Operations ceased due to inadequate cash flow o...       637791
                 Operations ceased because owner(s) retired               396582
                 Operations ceased because operated for a specif...       230357
                 Operations ceased because owner(s) illness or i...       167510
                 Operating status not reported                            120859
                 Operations ceased because owner(s) sold the bus...       100594
                 Operations ceased because owner(s) started anot...        94726
                 Operations ceased due to lack of business loans...        65349
                 Operations ceased because owner(s) died                   41318
                 Operations ceased due to lack of personal loans...        37452
                 Reason operations ceased not reported                     15859
                 Operations ceased because owner(s) military dep...         2738

                                                                     Percentage
Gender_ethnicity Ceased_reasons
White            Total reporting                                         100.00
                 Business is currently operating                          80.15
                 Operations ceased for another reason                      9.80
                 Operations ceased due to inadequate cash flow o...        4.35
                 Operations ceased because owner(s) retired                2.70
                 Operations ceased because operated for a specif...        1.57
                 Operations ceased because owner(s) illness or i...        1.14
                 Operating status not reported                             0.82
                 Operations ceased because owner(s) sold the bus...        0.69
                 Operations ceased because owner(s) started anot...        0.65
                 Operations ceased due to lack of business loans...        0.45
                 Operations ceased because owner(s) died                   0.28
                 Operations ceased due to lack of personal loans...        0.26
                 Reason operations ceased not reported                     0.11
                 Operations ceased because owner(s) military dep...        0.02

In [43]:
#Black
df_black = df_multi_gender.loc[pd.IndexSlice['Black or African American',:],:]
df_black = df_black.iloc[1:]
df_black = df_black.sort_values('Total_firms', ascending = False)
df_black['Percentage'] = round(df_black['Total_firms']/df_black.iloc[0,0]*100,2)
df_black

                                                                              Total_firms  \
Gender_ethnicity          Ceased_reasons
Black or African American Total reporting                                          840018
                          Business is currently operating                          569488
                          Operations ceased for another reason                     136491
                          Operations ceased due to inadequate cash flow o...        75350
                          Operating status not reported                             23224
                          Operations ceased because operated for a specif...        23146
                          Operations ceased because owner(s) illness or i...        21217
                          Operations ceased because owner(s) retired                13984
                          Operations ceased due to lack of business loans...        13483
                          Operations ceased due to lack of personal loans...        10434
                          Operations ceased because owner(s) started anot...         8073
                          Operations ceased because owner(s) sold the bus...         3369
                          Reason operations ceased not reported                      2651
                          Operations ceased because owner(s) died                    2300
                          Operations ceased because owner(s) military dep...          536

                                                                              Percentage
Gender_ethnicity          Ceased_reasons
Black or African American Total reporting                                         100.00
                          Business is currently operating                          67.79
                          Operations ceased for another reason                     16.25
                          Operations ceased due to inadequate cash flow o...        8.97
                          Operating status not reported                             2.76
                          Operations ceased because operated for a specif...        2.76
                          Operations ceased because owner(s) illness or i...        2.53
                          Operations ceased because owner(s) retired                1.66
                          Operations ceased due to lack of business loans...        1.61
                          Operations ceased due to lack of personal loans...        1.24
                          Operations ceased because owner(s) started anot...        0.96
                          Operations ceased because owner(s) sold the bus...        0.40
                          Reason operations ceased not reported                     0.32
                          Operations ceased because owner(s) died                   0.27
                          Operations ceased because owner(s) military dep...        0.06

In [44]:
#Asian
df_asian = df_multi_gender.loc[pd.IndexSlice['Asian',:],:]
df_asian = df_asian.iloc[1:]
df_asian = df_asian.sort_values('Total_firms', ascending = False)
df_asian['Percentage'] = round(df_asian['Total_firms']/df_asian.iloc[0,0]*100,2)
df_asian

                                                                     Total_firms  \
Gender_ethnicity Ceased_reasons
Asian            Total reporting                                         1110951
                 Business is currently operating                          876247
                 Operations ceased for another reason                     124217
                 Operations ceased due to inadequate cash flow o...        45193
                 Operations ceased because operated for a specif...        21023
                 Operations ceased because owner(s) retired                18735
                 Operations ceased because owner(s) sold the bus...        16099
                 Operating status not reported                             13014
                 Operations ceased because owner(s) started anot...        10021
                 Operations ceased because owner(s) illness or i...         8966
                 Operations ceased due to lack of business loans...         5485
                 Operations ceased due to lack of personal loans...         4070
                 Operations ceased because owner(s) died                    1877
                 Reason operations ceased not reported                      1530
                 Operations ceased because owner(s) military dep...          293

                                                                     Percentage
Gender_ethnicity Ceased_reasons
Asian            Total reporting                                         100.00
                 Business is currently operating                          78.87
                 Operations ceased for another reason                     11.18
                 Operations ceased due to inadequate cash flow o...        4.07
                 Operations ceased because operated for a specif...        1.89
                 Operations ceased because owner(s) retired                1.69
                 Operations ceased because owner(s) sold the bus...        1.45
                 Operating status not reported                             1.17
                 Operations ceased because owner(s) started anot...        0.90
                 Operations ceased because owner(s) illness or i...        0.81
                 Operations ceased due to lack of business loans...        0.49
                 Operations ceased due to lack of personal loans...        0.37
                 Operations ceased because owner(s) died                   0.17
                 Reason operations ceased not reported                     0.14
                 Operations ceased because owner(s) military dep...        0.03

In [45]:
#Hispanic
df_hispanic = df_multi_gender.loc[pd.IndexSlice['Hispanic',:],:]
df_hispanic = df_hispanic.iloc[1:]
df_hispanic = df_hispanic.sort_values('Total_firms', ascending = False)
df_hispanic['Percentage'] = round(df_hispanic['Total_firms']/df_hispanic.iloc[0,0]*100,2)
df_hispanic

                                                                     Total_firms  \
Gender_ethnicity Ceased_reasons
Hispanic         Total reporting                                         1261641
                 Business is currently operating                          923364
                 Operations ceased for another reason                     184612
                 Operations ceased due to inadequate cash flow o...        82773
                 Operations ceased because operated for a specif...        29788
                 Operating status not reported                             25024
                 Operations ceased because owner(s) retired                18338
                 Operations ceased because owner(s) illness or i...        17551
                 Operations ceased due to lack of business loans...        13001
                 Operations ceased because owner(s) started anot...        11092
                 Operations ceased due to lack of personal loans...         7501
                 Operations ceased because owner(s) sold the bus...         6730
                 Reason operations ceased not reported                      3348
                 Operations ceased because owner(s) died                    2429
                 Operations ceased because owner(s) military dep...          440

                                                                     Percentage
Gender_ethnicity Ceased_reasons
Hispanic         Total reporting                                         100.00
                 Business is currently operating                          73.19
                 Operations ceased for another reason                     14.63
                 Operations ceased due to inadequate cash flow o...        6.56
                 Operations ceased because operated for a specif...        2.36
                 Operating status not reported                             1.98
                 Operations ceased because owner(s) retired                1.45
                 Operations ceased because owner(s) illness or i...        1.39
                 Operations ceased due to lack of business loans...        1.03
                 Operations ceased because owner(s) started anot...        0.88
                 Operations ceased due to lack of personal loans...        0.59
                 Operations ceased because owner(s) sold the bus...        0.53
                 Reason operations ceased not reported                     0.27
                 Operations ceased because owner(s) died                   0.19
                 Operations ceased because owner(s) military dep...        0.03

In [ ]:
# Need to add a percentage column after Total_firms
# Find out reasons why different companies close their business
#df_multi_industry = df.set_index(['Industry', 'Ceased_reasons'])
#df_multi_industry