In [8]:
import pandas as pd
import numpy as np

In [9]:
df = pd.read_csv('Files/amount to open.csv')
columns = ['Industry', 'Gender_ethnicity', 'Capital_needed', 'Total_firms', 'Total_sales']
df.columns = columns
df = df.drop(columns = 'Total_sales')
df.head()

                Industry Gender_ethnicity      Capital_needed  Total_firms
0  Total for all sectors        All firms           All firms     27626360
1  Total for all sectors        All firms    Less than $5,000      5349989
2  Total for all sectors        All firms    $5,000 to $9,999      1342102
3  Total for all sectors        All firms  $10,000 to $24,999      1258060
4  Total for all sectors        All firms  $25,000 to $49,999       767882

In [10]:
#Check data types
df.dtypes

Industry            object
Gender_ethnicity    object
Capital_needed      object
Total_firms          int64
dtype: object

In [11]:
df_grouped_gender = df.groupby('Gender_ethnicity').sum()
df_grouped_gender = df_grouped_gender.sort_values('Total_firms', ascending = False)
df_grouped_gender['Percentage'] = round(df_grouped_gender['Total_firms']/df_grouped_gender.iloc[0,0]*100,2)
df_grouped_gender.head()

                                                    Total_firms  Percentage
Gender_ethnicity
All firms                                             124258797      100.00
All firms classifiable by gender, ethnicity, ra...    122505778       98.59
Non-Hispanic                                          110210582       88.69
Nonveteran                                            108338386       87.19
White                                                 101826846       81.95

In [12]:
#Remove All firms?
df_grouped_capital = df.groupby('Capital_needed').sum()
df_grouped_capital = df_grouped_capital.sort_values('Total_firms', ascending = False)
df_grouped_capital['Percentage'] = round(df_grouped_capital['Total_firms']/df_grouped_capital.iloc[0,0]*100,2)
df_grouped_capital

                          Total_firms  Percentage
Capital_needed
All firms                   765567621      100.00
Total reporting             473353274       61.83
Less than $5,000            149923986       19.58
Not applicable              117605902       15.36
Don't know                   59116432        7.72
$5,000 to $9,999             37605597        4.91
$10,000 to $24,999           35232427        4.60
$25,000 to $49,999           21494896        2.81
$50,000 to $99,999           18607489        2.43
$100,000 to $249,999         17561363        2.29
$250,000 to $999,999         11818303        1.54
Item not reported            10260155        1.34
$1,000,000 to $2,999,999      3178855        0.42
$3,000,000 or more            1207927        0.16

In [13]:
# Need to add a percentage column after Total_firms
df_multi_gender = df.set_index(['Gender_ethnicity', 'Capital_needed'])
df_multi_gender

                                                                                              Industry  \
Gender_ethnicity                                   Capital_needed
All firms                                          All firms                     Total for all sectors
                                                   Less than $5,000              Total for all sectors
                                                   $5,000 to $9,999              Total for all sectors
                                                   $10,000 to $24,999            Total for all sectors
                                                   $25,000 to $49,999            Total for all sectors
                                                   $50,000 to $99,999            Total for all sectors
                                                   $100,000 to $249,999          Total for all sectors
                                                   $250,000 to $999,999          Total for all sectors
                                                   $1,000,000 to $2,999,999      Total for all sectors
                                                   $3,000,000 or more            Total for all sectors
                                                   Don't know                    Total for all sectors
                                                   Not applicable                Total for all sectors
                                                   Total reporting               Total for all sectors
                                                   Item not reported             Total for all sectors
Female-owned                                       All firms                     Total for all sectors
                                                   Less than $5,000              Total for all sectors
                                                   $5,000 to $9,999              Total for all sectors
                                                   $10,000 to $24,999            Total for all sectors
                                                   $25,000 to $49,999            Total for all sectors
                                                   $50,000 to $99,999            Total for all sectors
                                                   $100,000 to $249,999          Total for all sectors
                                                   $250,000 to $999,999          Total for all sectors
                                                   $1,000,000 to $2,999,999      Total for all sectors
                                                   $3,000,000 or more            Total for all sectors
                                                   Don't know                    Total for all sectors
                                                   Not applicable                Total for all sectors
                                                   Total reporting               Total for all sectors
                                                   Item not reported             Total for all sectors
Male-owned                                         All firms                     Total for all sectors
                                                   Less than $5,000              Total for all sectors
...                                                                                                ...
Nonveteran, nonminority                            Total reporting           Industries not classified
                                                   Item not reported         Industries not classified
All firms classifiable by gender, ethnicity, ra... All firms                 Industries not classified
                                                   Less than $5,000          Industries not classified
                                                   $5,000 to $9,999          Industries not classified
                                                   $10,000 to $24,999        Industries not classified
                                                   $25,000 to $49,999        Industries not classified
                                                   $50,000 to $99,999        Industries not classified
                                                   $100,000 to $249,999      Industries not classified
                                                   $250,000 to $999,999      Industries not classified
                                                   $1,000,000 to $2,999,999  Industries not classified
                                                   $3,000,000 or more        Industries not classified
                                                   Don't know                Industries not classified
                                                   Not applicable            Industries not classified
                                                   Total reporting           Industries not classified
                                                   Item not reported         Industries not classified
Publicly held and other firms not classifiable ... All firms                 Industries not classified
                                                   Less than $5,000          Industries not classified
                                                   $5,000 to $9,999          Industries not classified
                                                   $10,000 to $24,999        Industries not classified
                                                   $25,000 to $49,999        Industries not classified
                                                   $50,000 to $99,999        Industries not classified
                                                   $100,000 to $249,999      Industries not classified
                                                   $250,000 to $999,999      Industries not classified
                                                   $1,000,000 to $2,999,999  Industries not classified
                                                   $3,000,000 or more        Industries not classified
                                                   Don't know                Industries not classified
                                                   Not applicable            Industries not classified
                                                   Total reporting           Industries not classified
                                                   Item not reported         Industries not classified

                                                                             Total_firms
Gender_ethnicity                                   Capital_needed
All firms                                          All firms                    27626360
                                                   Less than $5,000              5349989
                                                   $5,000 to $9,999              1342102
                                                   $10,000 to $24,999            1258060
                                                   $25,000 to $49,999             767882
                                                   $50,000 to $99,999             664661
                                                   $100,000 to $249,999           628046
                                                   $250,000 to $999,999           422634
                                                   $1,000,000 to $2,999,999       114022
                                                   $3,000,000 or more              43746
                                                   Don't know                    2124248
                                                   Not applicable                4197604
                                                   Total reporting              16912993
                                                   Item not reported              610593
Female-owned                                       All firms                     9878397
                                                   Less than $5,000              2048053
                                                   $5,000 to $9,999               360415
                                                   $10,000 to $24,999             283357
                                                   $25,000 to $49,999             156851
                                                   $50,000 to $99,999             122412
                                                   $100,000 to $249,999           106166
                                                   $250,000 to $999,999            58628
                                                   $1,000,000 to $2,999,999        14598
                                                   $3,000,000 or more               6061
                                                   Don't know                     533796
                                                   Not applicable                1919225
                                                   Total reporting               5609562
                                                   Item not reported              137082
Male-owned                                         All firms                    14844597
                                                   Less than $5,000              2792620
...                                                                                  ...
Nonveteran, nonminority                            Total reporting                  1298
                                                   Item not reported                  34
All firms classifiable by gender, ethnicity, ra... All firms                        7210
                                                   Less than $5,000                  343
                                                   $5,000 to $9,999                  140
                                                   $10,000 to $24,999                 81
                                                   $25,000 to $49,999                 70
                                                   $50,000 to $99,999                 82
                                                   $100,000 to $249,999               64
                                                   $250,000 to $999,999               67
                                                   $1,000,000 to $2,999,999            0
                                                   $3,000,000 or more                 16
                                                   Don't know                        410
                                                   Not applicable                    510
                                                   Total reporting                  1782
                                                   Item not reported                  53
Publicly held and other firms not classifiable ... All firms                          73
                                                   Less than $5,000                    0
                                                   $5,000 to $9,999                    0
                                                   $10,000 to $24,999                  0
                                                   $25,000 to $49,999                  0
                                                   $50,000 to $99,999                  0
                                                   $100,000 to $249,999                0
                                                   $250,000 to $999,999                0
                                                   $1,000,000 to $2,999,999            0
                                                   $3,000,000 or more                  0
                                                   Don't know                          0
                                                   Not applicable                      0
                                                   Total reporting                     0
                                                   Item not reported                  79

[29988 rows x 2 columns]

In [14]:
# Need to add a percentage column after Total_firms
# Find out most expensive industries to open and cheaper to open
# Compare it to the total sales
df_multi_industry = df.set_index(['Industry', 'Capital_needed'])
df_multi_industry

                                                                                     Gender_ethnicity  \
Industry                  Capital_needed
Total for all sectors     All firms                                                         All firms
                          Less than $5,000                                                  All firms
                          $5,000 to $9,999                                                  All firms
                          $10,000 to $24,999                                                All firms
                          $25,000 to $49,999                                                All firms
                          $50,000 to $99,999                                                All firms
                          $100,000 to $249,999                                              All firms
                          $250,000 to $999,999                                              All firms
                          $1,000,000 to $2,999,999                                          All firms
                          $3,000,000 or more                                                All firms
                          Don't know                                                        All firms
                          Not applicable                                                    All firms
                          Total reporting                                                   All firms
                          Item not reported                                                 All firms
                          All firms                                                      Female-owned
                          Less than $5,000                                               Female-owned
                          $5,000 to $9,999                                               Female-owned
                          $10,000 to $24,999                                             Female-owned
                          $25,000 to $49,999                                             Female-owned
                          $50,000 to $99,999                                             Female-owned
                          $100,000 to $249,999                                           Female-owned
                          $250,000 to $999,999                                           Female-owned
                          $1,000,000 to $2,999,999                                       Female-owned
                          $3,000,000 or more                                             Female-owned
                          Don't know                                                     Female-owned
                          Not applicable                                                 Female-owned
                          Total reporting                                                Female-owned
                          Item not reported                                              Female-owned
                          All firms                                                        Male-owned
                          Less than $5,000                                                 Male-owned
...                                                                                               ...
Industries not classified Total reporting                                     Nonveteran, nonminority
                          Item not reported                                   Nonveteran, nonminority
                          All firms                 All firms classifiable by gender, ethnicity, r...
                          Less than $5,000          All firms classifiable by gender, ethnicity, r...
                          $5,000 to $9,999          All firms classifiable by gender, ethnicity, r...
                          $10,000 to $24,999        All firms classifiable by gender, ethnicity, r...
                          $25,000 to $49,999        All firms classifiable by gender, ethnicity, r...
                          $50,000 to $99,999        All firms classifiable by gender, ethnicity, r...
                          $100,000 to $249,999      All firms classifiable by gender, ethnicity, r...
                          $250,000 to $999,999      All firms classifiable by gender, ethnicity, r...
                          $1,000,000 to $2,999,999  All firms classifiable by gender, ethnicity, r...
                          $3,000,000 or more        All firms classifiable by gender, ethnicity, r...
                          Don't know                All firms classifiable by gender, ethnicity, r...
                          Not applicable            All firms classifiable by gender, ethnicity, r...
                          Total reporting           All firms classifiable by gender, ethnicity, r...
                          Item not reported         All firms classifiable by gender, ethnicity, r...
                          All firms                 Publicly held and other firms not classifiable...
                          Less than $5,000          Publicly held and other firms not classifiable...
                          $5,000 to $9,999          Publicly held and other firms not classifiable...
                          $10,000 to $24,999        Publicly held and other firms not classifiable...
                          $25,000 to $49,999        Publicly held and other firms not classifiable...
                          $50,000 to $99,999        Publicly held and other firms not classifiable...
                          $100,000 to $249,999      Publicly held and other firms not classifiable...
                          $250,000 to $999,999      Publicly held and other firms not classifiable...
                          $1,000,000 to $2,999,999  Publicly held and other firms not classifiable...
                          $3,000,000 or more        Publicly held and other firms not classifiable...
                          Don't know                Publicly held and other firms not classifiable...
                          Not applicable            Publicly held and other firms not classifiable...
                          Total reporting           Publicly held and other firms not classifiable...
                          Item not reported         Publicly held and other firms not classifiable...

                                                    Total_firms
Industry                  Capital_needed
Total for all sectors     All firms                    27626360
                          Less than $5,000              5349989
                          $5,000 to $9,999              1342102
                          $10,000 to $24,999            1258060
                          $25,000 to $49,999             767882
                          $50,000 to $99,999             664661
                          $100,000 to $249,999           628046
                          $250,000 to $999,999           422634
                          $1,000,000 to $2,999,999       114022
                          $3,000,000 or more              43746
                          Don't know                    2124248
                          Not applicable                4197604
                          Total reporting              16912993
                          Item not reported              610593
                          All firms                     9878397
                          Less than $5,000              2048053
                          $5,000 to $9,999               360415
                          $10,000 to $24,999             283357
                          $25,000 to $49,999             156851
                          $50,000 to $99,999             122412
                          $100,000 to $249,999           106166
                          $250,000 to $999,999            58628
                          $1,000,000 to $2,999,999        14598
                          $3,000,000 or more               6061
                          Don't know                     533796
                          Not applicable                1919225
                          Total reporting               5609562
                          Item not reported              137082
                          All firms                    14844597
                          Less than $5,000              2792620
...                                                         ...
Industries not classified Total reporting                  1298
                          Item not reported                  34
                          All firms                        7210
                          Less than $5,000                  343
                          $5,000 to $9,999                  140
                          $10,000 to $24,999                 81
                          $25,000 to $49,999                 70
                          $50,000 to $99,999                 82
                          $100,000 to $249,999               64
                          $250,000 to $999,999               67
                          $1,000,000 to $2,999,999            0
                          $3,000,000 or more                 16
                          Don't know                        410
                          Not applicable                    510
                          Total reporting                  1782
                          Item not reported                  53
                          All firms                          73
                          Less than $5,000                    0
                          $5,000 to $9,999                    0
                          $10,000 to $24,999                  0
                          $25,000 to $49,999                  0
                          $50,000 to $99,999                  0
                          $100,000 to $249,999                0
                          $250,000 to $999,999                0
                          $1,000,000 to $2,999,999            0
                          $3,000,000 or more                  0
                          Don't know                          0
                          Not applicable                      0
                          Total reporting                     0
                          Item not reported                  79

[29988 rows x 2 columns]