In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('Files/ecommerce.csv')
columns = ['Industry', 'Gender_ethnicity', 'Ecommerce_sales', 'Total_firms', 'Total_sales']
df.columns = columns
df = df.drop(columns = 'Total_sales')
df.head()

                Industry Gender_ethnicity      Ecommerce_sales  Total_firms
0  Total for all sectors        All firms            All firms     27626360
1  Total for all sectors        All firms  No e-commerce sales     15787853
2  Total for all sectors        All firms         Less than 1%       175745
3  Total for all sectors        All firms             1% to 4%       177818
4  Total for all sectors        All firms             5% to 9%       122155

In [4]:
#Check data types
df.dtypes

Industry            object
Gender_ethnicity    object
Ecommerce_sales     object
Total_firms          int64
dtype: object

In [10]:
#Create df just with all firms
new_df = df.loc[df['Industry'] == 'Total for all sectors']
new_df = new_df.loc[new_df['Gender_ethnicity'] == 'All firms']
new_df = new_df.iloc[1:]
new_df

,Industry,Gender_ethnicity,Ecommerce_sales,Total_firms
1,Total for all sectors,All firms,No e-commerce sales,15787853
2,Total for all sectors,All firms,Less than 1%,175745
3,Total for all sectors,All firms,1% to 4%,177818
4,Total for all sectors,All firms,5% to 9%,122155
5,Total for all sectors,All firms,10% to 19%,149996
6,Total for all sectors,All firms,20% to 49%,177630
7,Total for all sectors,All firms,50% to 99%,289550
8,Total for all sectors,All firms,100%,215826
9,Total for all sectors,All firms,Don't know,249092
10,Total for all sectors,All firms,Total reporting,17347429
11,Total for all sectors,All firms,E-commerce not reported,176157
12,Total for all sectors,All firms,Percent e-commerce not reported,1764

In [11]:
#Remove all firms?
df_grouped = new_df.groupby('Ecommerce_sales').sum()
df_grouped = df_grouped.sort_values('Total_firms', ascending = False)
df_grouped['Percentage'] = round(df_grouped['Total_firms']/df_grouped.iloc[0,0]*100,2)
df_grouped

                                 Total_firms  Percentage
Ecommerce_sales
Total reporting                     17347429      100.00
No e-commerce sales                 15787853       91.01
50% to 99%                            289550        1.67
Don't know                            249092        1.44
100%                                  215826        1.24
1% to 4%                              177818        1.03
20% to 49%                            177630        1.02
E-commerce not reported               176157        1.02
Less than 1%                          175745        1.01
10% to 19%                            149996        0.86
5% to 9%                              122155        0.70
Percent e-commerce not reported         1764        0.01

In [12]:
# Need to add a percentage column after Total_firms
df_multi_gender = df.set_index(['Gender_ethnicity', 'Ecommerce_sales'])
df_multi_gender = df_multi_gender.loc[df_multi_gender['Industry'] == 'Total for all sectors']
df_multi_gender = df_multi_gender.drop(columns = 'Industry')
df_multi_gender

                                                                                    Total_firms
Gender_ethnicity                                   Ecommerce_sales
All firms                                          All firms                           27626360
                                                   No e-commerce sales                 15787853
                                                   Less than 1%                          175745
                                                   1% to 4%                              177818
                                                   5% to 9%                              122155
                                                   10% to 19%                            149996
                                                   20% to 49%                            177630
                                                   50% to 99%                            289550
                                                   100%                                  215826
                                                   Don't know                            249092
                                                   Total reporting                     17347429
                                                   E-commerce not reported               176157
                                                   Percent e-commerce not reported         1764
Female-owned                                       All firms                            9878397
                                                   No e-commerce sales                  5113985
                                                   Less than 1%                           71059
                                                   1% to 4%                               68996
                                                   5% to 9%                               42252
                                                   10% to 19%                             50475
                                                   20% to 49%                             61982
                                                   50% to 99%                             97952
                                                   100%                                   79388
                                                   Don't know                             93659
                                                   Total reporting                      5680360
                                                   E-commerce not reported                66285
                                                   Percent e-commerce not reported          612
Male-owned                                         All firms                           14844597
                                                   No e-commerce sales                  8711340
                                                   Less than 1%                           78133
                                                   1% to 4%                               79810
...                                                                                         ...
Nonveteran, nonminority                            Don't know                            178420
                                                   Total reporting                     11752440
                                                   E-commerce not reported                88722
                                                   Percent e-commerce not reported         1306
All firms classifiable by gender, ethnicity, ra... All firms                           27179380
                                                   No e-commerce sales                 15477698
                                                   Less than 1%                          172460
                                                   1% to 4%                              175111
                                                   5% to 9%                              120611
                                                   10% to 19%                            148280
                                                   20% to 49%                            175344
                                                   50% to 99%                            286010
                                                   100%                                  214183
                                                   Don't know                            237681
                                                   Total reporting                     17009134
                                                   E-commerce not reported               166664
                                                   Percent e-commerce not reported         1755
Publicly held and other firms not classifiable ... All firms                             446980
                                                   No e-commerce sales                   310156
                                                   Less than 1%                            3285
                                                   1% to 4%                                2707
                                                   5% to 9%                                1543
                                                   10% to 19%                              1716
                                                   20% to 49%                              2286
                                                   50% to 99%                              3540
                                                   100%                                    1643
                                                   Don't know                             11411
                                                   Total reporting                       338295
                                                   E-commerce not reported                 9493
                                                   Percent e-commerce not reported            9

[1326 rows x 1 columns]

In [14]:
#Female
df_female = df_multi_gender.loc[pd.IndexSlice['Female-owned',:],:]
df_female = df_female.iloc[1:]
df_female = df_female.sort_values('Total_firms', ascending = False)
df_female['Percentage'] = round(df_female['Total_firms']/df_female.iloc[0,0]*100,2)
df_female

                                                  Total_firms  Percentage
Gender_ethnicity Ecommerce_sales
Female-owned     Total reporting                      5680360      100.00
                 No e-commerce sales                  5113985       90.03
                 50% to 99%                             97952        1.72
                 Don't know                             93659        1.65
                 100%                                   79388        1.40
                 Less than 1%                           71059        1.25
                 1% to 4%                               68996        1.21
                 E-commerce not reported                66285        1.17
                 20% to 49%                             61982        1.09
                 10% to 19%                             50475        0.89
                 5% to 9%                               42252        0.74
                 Percent e-commerce not reported          612        0.01

In [15]:
#Male
df_male = df_multi_gender.loc[pd.IndexSlice['Male-owned',:],:]
df_male = df_male.iloc[1:]
df_male = df_male.sort_values('Total_firms', ascending = False)
df_male['Percentage'] = round(df_male['Total_firms']/df_male.iloc[0,0]*100,2)
df_male

                                                  Total_firms  Percentage
Gender_ethnicity Ecommerce_sales
Male-owned       Total reporting                      9460736      100.00
                 No e-commerce sales                  8711340       92.08
                 50% to 99%                            142919        1.51
                 Don't know                            118200        1.25
                 100%                                  105083        1.11
                 E-commerce not reported                92833        0.98
                 20% to 49%                             87356        0.92
                 1% to 4%                               79810        0.84
                 Less than 1%                           78133        0.83
                 10% to 19%                             75863        0.80
                 5% to 9%                               60985        0.64
                 Percent e-commerce not reported         1045        0.01

In [16]:
#White
df_white = df_multi_gender.loc[pd.IndexSlice['White',:],:]
df_white = df_white.iloc[1:]
df_white = df_white.sort_values('Total_firms', ascending = False)
df_white['Percentage'] = round(df_white['Total_firms']/df_white.iloc[0,0]*100,2)
df_white

                                                  Total_firms  Percentage
Gender_ethnicity Ecommerce_sales
White            Total reporting                     14663863      100.00
                 No e-commerce sales                 13290967       90.64
                 50% to 99%                            258089        1.76
                 Don't know                            210758        1.44
                 100%                                  187686        1.28
                 1% to 4%                              158926        1.08
                 20% to 49%                            157264        1.07
                 Less than 1%                          155357        1.06
                 10% to 19%                            134036        0.91
                 E-commerce not reported               121453        0.83
                 5% to 9%                              109271        0.75
                 Percent e-commerce not reported         1510        0.01

In [17]:
#Black
df_black = df_multi_gender.loc[pd.IndexSlice['Black or African American',:],:]
df_black = df_black.iloc[1:]
df_black = df_black.sort_values('Total_firms', ascending = False)
df_black['Percentage'] = round(df_black['Total_firms']/df_black.iloc[0,0]*100,2)
df_black

                                                           Total_firms  \
Gender_ethnicity          Ecommerce_sales
Black or African American Total reporting                       840359
                          No e-commerce sales                   784874
                          E-commerce not reported                22883
                          Don't know                              9752
                          50% to 99%                              9462
                          Less than 1%                            8520
                          1% to 4%                                6690
                          100%                                    6662
                          20% to 49%                              6102
                          10% to 19%                              4081
                          5% to 9%                                4072
                          Percent e-commerce not reported          145

                                                           Percentage
Gender_ethnicity          Ecommerce_sales
Black or African American Total reporting                      100.00
                          No e-commerce sales                   93.40
                          E-commerce not reported                2.72
                          Don't know                             1.16
                          50% to 99%                             1.13
                          Less than 1%                           1.01
                          1% to 4%                               0.80
                          100%                                   0.79
                          20% to 49%                             0.73
                          10% to 19%                             0.49
                          5% to 9%                               0.48
                          Percent e-commerce not reported        0.02

In [18]:
#Asian
df_asian = df_multi_gender.loc[pd.IndexSlice['Asian',:],:]
df_asian = df_asian.iloc[1:]
df_asian = df_asian.sort_values('Total_firms', ascending = False)
df_asian['Percentage'] = round(df_asian['Total_firms']/df_asian.iloc[0,0]*100,2)
df_asian

                                                  Total_firms  Percentage
Gender_ethnicity Ecommerce_sales
Asian            Total reporting                      1111430      100.00
                 No e-commerce sales                  1028258       92.52
                 100%                                   17881        1.61
                 50% to 99%                             15843        1.43
                 Don't know                             12841        1.16
                 E-commerce not reported                12535        1.13
                 20% to 49%                              9920        0.89
                 10% to 19%                              7596        0.68
                 Less than 1%                            6708        0.60
                 1% to 4%                                6698        0.60
                 5% to 9%                                5642        0.51
                 Percent e-commerce not reported           43        0.00

In [19]:
#Hispanic
df_hispanic = df_multi_gender.loc[pd.IndexSlice['Hispanic',:],:]
df_hispanic = df_hispanic.iloc[1:]
df_hispanic = df_hispanic.sort_values('Total_firms', ascending = False)
df_hispanic['Percentage'] = round(df_hispanic['Total_firms']/df_hispanic.iloc[0,0]*100,2)
df_hispanic

                                                  Total_firms  Percentage
Gender_ethnicity Ecommerce_sales
Hispanic         Total reporting                      1262033      100.00
                 No e-commerce sales                  1191056       94.38
                 E-commerce not reported                24632        1.95
                 50% to 99%                             13481        1.07
                 Don't know                             13000        1.03
                 100%                                   11384        0.90
                 20% to 49%                              7858        0.62
                 1% to 4%                                7090        0.56
                 Less than 1%                            6772        0.54
                 10% to 19%                              5925        0.47
                 5% to 9%                                5344        0.42
                 Percent e-commerce not reported          123        0.01

In [13]:
# Need to add a percentage column after Total_firms
# Find out reasons how different companies work with ecom
#df_multi_industry = df.set_index(['Industry', 'Ecommerce_sales'])
#df_multi_industry